import Image from "next/image";
import { Quicksand } from "next/font/google";
//logo
import logo from '@/assets/react-quiz-logo.svg';;
//CSS
import "./globals.css";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable:"--font-quicksand"
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body className="bg-[#2b2737] p-4">
        <main className={`${quicksand.variable} font-quicksand max-w-[900px] w-full m-auto flex flex-col items-center`}>
          <Image className="h-[80px] sm:h-full" src={logo} alt="logo" />
          {children}
        </main>
      </body>
      
    </html>
  )
}
